apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template: # Ici on d√©finit le Pod
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mon-conteneur
        image: admin-portal:latest # Nom de ton image Docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
